services:
  mysql:
    image: mysql:8.0
    container_name: gin-admin-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "GinAdminMysql"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", '-h', "localhost", '-u', "root", '-p123456']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-admin-backend
    restart: unless-stopped
    ports: 
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy


  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: gin-admin-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:

