services:
  mysql:
    image: mysql:8.0
    container_name: gin-admin-mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "GinAdminMysql"
    volumes:
      - gin-admin-mysql:/var/lib/mysql

volumes:
  gin-admin-mysql: