timezone: "Asia/Shanghai"

jwt:
  secret_key: "your-256-bit-secret-key"
  ttl: "2h"

mysql:
  enable: true
  host: 127.0.0.1
  port: 3306
  database: GinAdminMysql
  username: root
  password: 123456



redis:
  enable: false
